{
  "id": "GHSA-g5j6-r3x9-gf2m",
  "summary": "Cross-site scripting in Contentful",
  "details": "Contentful through 2020-05-21 for Python allows reflected XSS, as demonstrated by the api parameter to the-example-app.py.",
  "aliases": [
    "CVE-2020-13258"
  ],
  "modified": "2023-04-11T01:42:09.000722Z",
  "published": "2021-06-18T18:32:20Z",
  "database_specific": {
    "nvd_published_at": "2020-05-21T17:15:00Z",
    "github_reviewed_at": "2021-05-14T21:45:06Z",
    "severity": "MODERATE",
    "github_reviewed": true,
    "cwe_ids": [
      "CWE-79"
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-13258"
    },
    {
      "type": "WEB",
      "url": "https://github.com/contentful/the-example-app.py/issues/44"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "contentful",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/contentful"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.12.4"
            }
          ]
        }
      ],
      "versions": [
        "1.0.0",
        "1.0.1",
        "1.0.2",
        "1.0.3",
        "1.1.0",
        "1.1.1",
        "1.10.1",
        "1.10.2",
        "1.11.1",
        "1.11.2",
        "1.11.3",
        "1.11.4",
        "1.12.0",
        "1.12.1",
        "1.12.2",
        "1.12.3",
        "1.2.0",
        "1.3.0",
        "1.4.1",
        "1.4.2",
        "1.4.3",
        "1.5.0",
        "1.6.0",
        "1.7.0",
        "1.8.0",
        "1.9.0",
        "1.9.1"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/06/GHSA-g5j6-r3x9-gf2m/GHSA-g5j6-r3x9-gf2m.json"
      }
    }
  ],
  "schema_version": "1.4.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
    }
  ]
}